monitor:
  # 要监控的目录路径
  paths:
    - "/var/log"
  # 文件匹配模式
  patterns:
    - "clamd.*"
  
matcher:
  # 正则表达式规则
  rules:
    - pattern: ".*FOUND"
      level: "error"
    - pattern: ".*OK"
      level: "warning"

position:
  # 文件位置记录文件
  store_path: "positions.json"
  # 更新间隔（秒）
  update_interval: 2

system:
  # 内存限制（MB）
  memory_limit: 10
  # 读取缓冲区大小（bytes）
  buffer_size: 4096
  pid_file: "/var/run/clamguardian.pid"  # 可选，默认值为 /var/run/clamguardian.pid

metrics:
  enabled: true
  port: 2112
  path: "/metrics"

log:
  path: "logs/clamguardian.log"
  format: "json"  # 可选值: "text" 或 "json"
  level: "info"   # 可选值: "debug", "info", "warn", "error"
  max_size: 100
  max_backups: 3
  max_age: 7

status:
  interval: 3     # 秒
